from fastai import* 
from fastai.vision import* 
import os
from win32com.client import Dispatch
#import pyttsx3;
#import subprocess
def neyro():
    classes = ['Abyssinian',
 'Bengal',
 'Birman',
 'Bombay',
 'British_Shorthair',
 'Egyptian_Mau',
 'Maine_Coon',
 'Persian',
 'Ragdoll',
 'Russian_Blue',
 'Siamese',
 'Sphynx',
 'american_bulldog',
 'american_pit_bull_terrier',
 'apple',
 'aspen',
 'basset_hound',
 'bath',
 'beagle',
 'bed',
 'bench',
 'birch',
 'book',
 'bottle',
 'box',
 'boxer',
 'bush',
 'cabbage',
 'carp',
 'carrot',
 'chair',
 'chihuahua',
 'cod',
 'comb',
 'crow',
 'cucumber',
 'cup',
 'eggplant',
 'english_cocker_spaniel',
 'english_setter',
 'envelope',
 'fir',
 'fork',
 'german_shorthaired',
 'glass',
 'glasses',
 'great_pyrenees',
 'hanger',
 'havanese',
 'horse',
 'house',
 'japanese_chin',
 'keeshond',
 'kettle',
 'knife',
 'laptop',
 'lawn',
 'lemon',
 'leonberger',
 'maple',
 'melon',
 'miniature_pinscher',
 'newfoundland',
 'oak',
 'offroad car',
 'orange',
 'parrot',
 'passenger car',
 'pencil',
 'pepper',
 'pigeon',
 'pine',
 'plate',
 'plush toy',
 'pomeranian',
 'potato',
 'pug',
 'pumpkin',
 'racing car',
 'reedmace',
 'saint_bernard',
 'samoyed',
 'scottish_terrier',
 'shiba_inu',
 'snake',
 'soap',
 'socket',
 'sofa',
 'sparrow',
 'spoon',
 'squirrel',
 'staffordshire_bull_terrier',
 'sturgeon',
 'swallow',
 'table',
 'toaster',
 'tomato',
 'toothbrush',
 'toothpaste',
 'trout',
 'truck',
 'vacuum cleaner',
 'wallet',
 'watermelon',
 'wheaten_terrier',
 'willow',
 'yorkshire_terrier']
    path = Path(os.path.dirname(__file__))
    data2 = ImageDataBunch.single_from_classes(path, classes, ds_tfms= get_transforms(), size= 224 ).normalize(imagenet_stats)
    learn = cnn_learner( data2, models.resnet50)
    learn.load('project2')
    img = open_image (os.path.dirname(__file__) + "\\img.png")
    try:
        pred_class, pred_idx, outputs = learn.predict(img)
    except: p = 0
    speak = Dispatch("SAPI.SpVoice")
    speak.Speak(str(pred_class))
    os.remove(os.path.dirname(__file__) + "\\img.png")

